FROM oven/bun:1 AS builder

WORKDIR /repo

COPY . .

RUN bun install --frozen-lockfile

RUN bunx turbo build --filter=@portfolio/web

RUN find apps/web -name "entry.mjs"

FROM oven/bun:1-slim

WORKDIR /app

COPY --from=builder /repo/package.json .
COPY --from=builder /repo/node_modules ./node_modules
COPY --from=builder /repo/apps/web ./apps/web
COPY --from=builder /repo/packages ./packages

ENV PORT=4321
ENV HOST=0.0.0.0

CMD ["bun","apps/web/dist/server/entry.mjs"]
