FROM oven/bun:1 AS builder

WORKDIR /repo

COPY . .

RUN bun install --frozen-lockfile

RUN bunx turbo build --filter=@portfolio/dashboard

FROM oven/bun:1-slim

WORKDIR /app

COPY --from=builder /repo/package.json .
COPY --from=builder /repo/node_modules ./node_modules
COPY --from=builder /repo/apps/dashboard ./apps/dashboard
COPY --from=builder /repo/packages ./packages

CMD ["bun","apps/dashboard/dist/index.js"]