FROM oven/bun:1 AS builder

WORKDIR /repo

COPY . .

RUN bun install --frozen-lockfile

RUN bunx turbo build --filter=@portfolio/api

FROM oven/bun:1-slim

WORKDIR /app

COPY --from=builder /repo/package.json .
COPY --from=builder /repo/node_modules ./node_modules
COPY --from=builder /repo/apps/api ./apps/api
COPY --from=builder /repo/packages ./packages

ENV PORT=3001
ENV HOST=0.0.0.0

CMD ["bun","apps/api/dist/index.js"]